// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceHub.Data;

#nullable disable

namespace ServiceHub.Data.Migrations
{
    [DbContext(typeof(ServiceHubDbContext))]
    [Migration("20250806062622_AddDataConstantsToEntities")]
    partial class AddDataConstantsToEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99049752-95b1-477d-944a-f34589d31b09",
                            ConcurrencyStamp = "04e8c6c7-02b1-4420-93e9-352c7debe61d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0c8b3e8e-c25e-44d7-84f9-2c7b5a1b3e4f",
                            ConcurrencyStamp = "f14f9a98-c213-4e6e-8683-93a2a51129fc",
                            Name = "BusinessUser",
                            NormalizedName = "BUSINESSUSER"
                        },
                        new
                        {
                            Id = "1d9c4f9f-a36a-4d6b-b5e0-3d8c6b2a5f7e",
                            ConcurrencyStamp = "8a251694-6d42-4944-b938-1a64959afcbc",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            RoleId = "99049752-95b1-477d-944a-f34589d31b09"
                        },
                        new
                        {
                            UserId = "3f8b6c7d-e5f6-4g8h-i9j0-1k2l3m4n5o6p",
                            RoleId = "0c8b3e8e-c25e-44d7-84f9-2c7b5a1b3e4f"
                        },
                        new
                        {
                            UserId = "4g9c7d8e-f6g7-4h9i-j0k1-2l3m4n5o6p7q",
                            RoleId = "1d9c4f9f-a36a-4d6b-b5e0-3d8c6b2a5f7e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BusinessExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastServiceCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54f2ffb5-187d-4705-8ba7-eced5295d1b6",
                            Email = "admin@servicehub.com",
                            EmailConfirmed = true,
                            IsBusiness = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SERVICEHUB.COM",
                            NormalizedUserName = "ADMINUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEHDyY+bWGj5b4NCEQ22sdDwwgOXUGzd14Jna1PWwgUGuAT5uDIm3rppo3ro8FK2jdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f66ba631-9742-46e6-aff2-88b606948423",
                            TwoFactorEnabled = false,
                            UserName = "adminuser"
                        },
                        new
                        {
                            Id = "3f8b6c7d-e5f6-4g8h-i9j0-1k2l3m4n5o6p",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c82364e-67b9-4d2a-8eb8-ae1c9f23a9f5",
                            Email = "business@servicehub.com",
                            EmailConfirmed = true,
                            IsBusiness = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BUSINESS@SERVICEHUB.COM",
                            NormalizedUserName = "BUSINESSUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDvbXwCicbCkwIgkmtihHz+xB9VVltKmrmML+xT00yGnQH57wYtvDJ18a/xQQWvCXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "838cd190-3e91-4fed-a54e-a9904753be41",
                            TwoFactorEnabled = false,
                            UserName = "businessuser"
                        },
                        new
                        {
                            Id = "4g9c7d8e-f6g7-4h9i-j0k1-2l3m4n5o6p7q",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a293b56-50f1-41cd-978b-416592f6e2ed",
                            Email = "user@servicehub.com",
                            EmailConfirmed = true,
                            IsBusiness = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@SERVICEHUB.COM",
                            NormalizedUserName = "REGULARUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEKY0c1iTAtyn5l0NSl/Trn0F1PZ9MRgXUKO2ErqWpvmLb0X7LhGC0RoeprNGZ2paXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1e26423-0fa5-40b3-af80-87144b999844",
                            TwoFactorEnabled = false,
                            UserName = "regularuser"
                        });
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 203, DateTimeKind.Utc).AddTicks(577),
                            Description = "Инструменти за работа с документи.",
                            Name = "Документи"
                        },
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 203, DateTimeKind.Utc).AddTicks(584),
                            Description = "Различни общи инструменти.",
                            Name = "Инструменти"
                        });
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d4ae40b-c305-47b7-beed-163c4a0aeb40"),
                            AccessType = 1,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5030),
                            CategoryId = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5027),
                            Description = "Конвертира различни файлови формати (напр. PDF към DOCX, JPG към PNG).",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"FileConverter\", \"endpoint\": \"/api/FileConverter/convert\", \"method\": \"POST\"}",
                            Title = "Конвертор на Файлове",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("e11e539c-0290-4171-b606-16628d1790b0"),
                            AccessType = 1,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5045),
                            CategoryId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5045),
                            Description = "Преобразува код между програмни езици (напр. C# към Python).",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"CodeConverter\", \"endpoint\": \"/api/CodeConverter/convert\", \"method\": \"POST\"}",
                            Title = "Конвертор на Кодови Снипети",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("c10de2fa-b49b-4c0d-9e8f-142b3cd40e6f"),
                            AccessType = 0,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5051),
                            CategoryId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5051),
                            Description = "Преобразува текст в главни букви, малки букви или заглавен регистър.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"TextCaseConverter\", \"endpoint\": \"/api/TextCaseConverter/convert\", \"method\": \"POST\"}",
                            Title = "Конвертор на Текст (Главни/Малки букви)",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("f0c72c7b-709d-44b7-81c1-1e5ab73305ec"),
                            AccessType = 2,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5056),
                            CategoryId = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5056),
                            Description = "Въвеждаш данни и получаваш готово CV в PDF формат.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"CVGenerator\", \"endpoint\": \"/api/CVGenerator/generate\", \"method\": \"POST\"}",
                            Title = "Автоматично CV/Резюме",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("f5e402c0-91ba-4f8e-97d0-3b443fe10d3c"),
                            AccessType = 0,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5061),
                            CategoryId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5060),
                            Description = "Генерира силни, случайни пароли с конфигурируеми опции.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"PasswordGenerator\", \"endpoint\": \"/api/PasswordGenerator/generate\", \"method\": \"GET\"}",
                            Title = "Генератор на Случайни Пароли",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("b422f89b-e7a3-4130-b899-7b56010007e0"),
                            AccessType = 2,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5067),
                            CategoryId = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5067),
                            Description = "Въвеждаш данни и получаваш изчислена фактура.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"InvoiceGenerator\", \"endpoint\": \"/api/InvoiceGenerator/generate\", \"method\": \"POST\"}",
                            Title = "Генератор на Инвойси/Фактури",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("2ef43d87-d749-4d7d-9b7d-f7c4f527bea7"),
                            AccessType = 2,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5072),
                            CategoryId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5071),
                            Description = "Изчислява ROI, бюджети, прогнозни приходи и разходи.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"FinancialCalculator\", \"endpoint\": \"/api/FinancialCalculator/calculate\", \"method\": \"POST\"}",
                            Title = "Финансов Калкулатор / Анализатор",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("3a7b8b0c-1d2e-4f5a-a837-3d5e9f1a2b0c"),
                            AccessType = 0,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5086),
                            CategoryId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-000000000002"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5086),
                            Description = "Преброява думи, символи и редове във въведен текст.",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"WordCharacterCounter\", \"endpoint\": \"/api/WordCharacter/count\", \"method\": \"POST\"}",
                            Title = "Брояч на Думи и Символи",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = new Guid("8edc2d04-00f5-4630-b5a9-4fa499fc7210"),
                            AccessType = 2,
                            ApprovedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            ApprovedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5091),
                            CategoryId = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedByUserId = "2e7a5b6c-d4e5-4f7g-h8i9-0j1k2l3m4n5o",
                            CreatedOn = new DateTime(2025, 8, 6, 6, 26, 21, 205, DateTimeKind.Utc).AddTicks(5090),
                            Description = "Генерира автоматично договори с шаблони (наем, труд и др.).",
                            IsApproved = true,
                            IsTemplate = false,
                            ServiceConfigJson = "{\"toolName\": \"ContractGenerator\", \"endpoint\": \"/api/ContractGenerator/generate\", \"method\": \"POST\"}",
                            Title = "Генератор на Договори",
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Favorite", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.Service", "Service")
                        .WithMany("Favorites")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Review", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.Service", "Service")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Service", b =>
                {
                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServiceHub.Data.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceHub.Data.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedServices")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CreatedServices");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ServiceHub.Data.Models.Service", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
